### ISSUE TITLE
Type not being detected

### ISSUE THREAD

**Issue by AznStevy** [AznStevy/bme590hrm#3]
https://github.com/AznStevy/bme590hrm/blob/6687a146db16b168ad9dbff2df9a04c096cf91ce/tests/test_file_handler.py#L53

When I try to check if a string is a dict, it says that the string is a dict which fails one of my tests. Not what's going on.

**Comment by suyashkumar** [comment]
Hiya @AznStevy. I've reproduced your existing below for easy reference:

https://github.com/AznStevy/bme590hrm/blob/6687a146db16b168ad9dbff2df9a04c096cf91ce/tests/test_file_handler.py#L49-L64

What is happening here is that `ecg_file.write_data(data, test_file_path)` is in fact _correctly_ raising a `TypeError`, however you are "catching" that error in your `except TypeError` block. So when `ecg_file.write_data(data, test_file_path)` throws the TypeError in your test, you execute the `except` block which runs the code `assert True`. Since this is always valid, the program will *not* fail as expected and will continue. So what happens next is that your program actually continues on to line 62 unimpeded, and fails on the assertion on line 64 instead.

Note the output pytest gives you:
```pytest
data = 'This is a string'

    @pytest.mark.parametrize("data", [
        ({}),
        ({"name": "Bob"}),
        ({"_id": "42", "favorite_nums": [2, 3, 4]}),
        (str("This is a string"))])
    def test_write_data(data):
        test_file_path = "tests/test_data/test_json.json"
        ecg_file = FileHandler("/test_data/test1.csv", initialize=False)
        try:
            ecg_file.write_data(data, test_file_path)
        except TypeError:
            assert True

        with open(test_file_path) as json_data:
            file_data = json.load(json_data)
>           assert file_data == data
E           AssertionError: assert {'_id': '42', 'favorite_nums': [2, 3, 4]} == 'This is a string'

tests/test_file_handler.py:64: AssertionError
```

What it seems like you want to do instead is ensure that a `TypeError` is correctly raised when the input is not a dictionary to your `write_data` function. You can break this out into another test function that tests a variety of non-string function inputs and ensures the `TypeError` is correctly thrown. We covered how to do this in class and you can find an example in [the lecture notes here](https://github.com/mlp6/Medical-Software-Design/blob/master/Lectures/Exceptions_ExitCodes_Logging.md#testing-that-your-code-throws-an-exception). Let me know if you have any questions on that! 

Also FYI, I noticed your build was failing for some reasons. See #4.
